apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kapilkhubchandani
  namespace: bethany
spec:
  dnsNames:
  - kapilkhubchandani.de  
  issuerRef:
    name: bethany-lets-encrypt
  secretName: kk-secret
