# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      Database__ServerName: sqlserver
      Database__Port: 1433
      Database__UserName: sa
      Database__Password: P@ssw0rd1$
      Database__UseLocalDatabase: "false"
    
    container:
       image: mcr.microsoft.com/dotnet/sdk:7.0


    services:
      sqlserver:
         image: mcr.microsoft.com/mssql/server:2019-latest
         env:
           SA_PASSWORD: ${{env.Database__Password}}
           ACCEPT_EUCLA: Y
         ports:
           - "1433:1433"
  

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger trx --results-directory "TestResults"
    
    - name: Upload Test Result
      uses: actions/upload-artifact@v3
      if: ${{always()}}
      with:
        name: test-results
        path: TestResults
  
 