name: "Zap Test"
on: 
    workflow_dispatch:

jobs:
    scan:
        runs-on: ubuntu-latest
        steps:
        - name: ZAP Scan
          uses: zaproxy/action-full-scan@v0.8.0
          with:
            target: 'http://pieshop.kapilkhubchandani.de/'